name: CI

on:
  push:
    branches: [ main ]


jobs:
  call-release-workflow:
    uses: josue-r/Pipelines/.github/workflows/release.yml@release
    secrets: inherit
    with:
      port: 4202
      tags: "thistag"
