name: RELEASE

## environments approach
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Your tag input'
      port:
        type: string
      environment:
        type: choice
        options:
          - qa
          - dev
  workflow_call:
    inputs:
      port:
        type: string
      tags:
        type: string
      environment:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      qa_servers: ${{ steps.qa_servers.outputs.qa_servers }}
    steps:
      - name: Set up qa servers
        id: qa_servers
        run: |
          qa_servers=$(echo ${{ vars.SERVER }} | jq -Rrc 'split(",")')
          echo "qa_servers=$qa_servers" >> "$GITHUB_OUTPUT"
          echo $qa_servers

  deploy:
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment != 'dev') }}
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        server: ${{ fromJSON(needs.build.outputs.qa_servers) }}
    steps:
      - name: Run validation
        run: |
          echo "event name is: ${{ github.event_name }}"
          echo "port: ${{ inputs.port }}"
          echo "Current QA Server (from matrix): ${{ matrix.server }}"
          # echo ${{ vars.SERVER }}


  # qa:
  #   if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.environment != 'dev') }}
  #   runs-on: ubuntu-latest
  #   environment: ${{ inputs.environment }}
  #   steps:
  #   - name: Run validation
  #     run: |
  #       echo "event name is:" ${{ github.event_name }} 
  #       echo ${{ inputs.port }}
  #       echo ${{ vars.SERVER}}



## manual and reusable workflow approach
# on:
#   workflow_dispatch:
#     inputs:
#       tags:
#         type: choice
#         options:
#           - qa
#           - prod
#       port:
#         type: string
#   workflow_call:
#     inputs:
#       port:
#         type: string
#       tags:
#         type: string


# jobs:
#   triage:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Run hello release
#       run: |
#         # Check the inputs based on the event type.
#         # For workflow_dispatch, inputs are in github.event.inputs
#         # For workflow_call, they are accessible via inputs.
#         if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
#           PORT="${{ github.event.inputs.port }}"
#           TAGS="${{ github.event.inputs.tags }}"
#         else
#           PORT="${{ inputs.port }}"
#           TAGS="${{ inputs.tags }}"
#         fi

#         echo "Tag selected is: ${TAGS}"
#         # If port is 'qa' and tags is empty, set a default tag.
#         if [[ "${TAGS}" == "qa" && -z "${PORT}" ]]; then
#           PORT="default_port_22"
#           echo "No port provided for qa; using default: ${PORT}"
#         fi
        
#         # Export PORT so that subsequent steps can use it.
#         echo "port=${PORT}" >> $GITHUB_ENV

#     - name: Run hello release
#       run: |
#         # Here, echo using the selected port and tags.
#         if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
#           echo "Port github event: ${{ github.event.inputs.port }}"
#         else
#           echo "Port inputs: ${{ inputs.port }}"
#         fi
#         echo "Port regular: ${port}"

